---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: add common user to all servers
    tags: always
    user:
      name: ops_user
      group: root

  - name: copy SSH for ops_user 
    tags: always
    authorized_key:
     user: ops_user
     key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILbrN5h0evHn3EjZFiUtVTG2aYVNdHAjH1Q5VSgyMZbX ansible"


  - name: add into sudoers 
    tags: always
    copy:
     src: file/ops_user_sudoers    # create this file with passwordless entry for sudoers anwhere in server. so that it can be copied.
     dest: "/etc/sudoers.d/ops_user"
     owner: root
     group: root
     mode: 0440
