---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
     update_cache: yes
    when: ansible_distribution == "CentOS"  

  - name: install httpd and php package
    yum:
      name:
       - httpd
       - php
      state: latest
    when: ansible_distribution == "CentOS"


  - name: Update repository index
    apt:
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: 
       - apache2
       - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb on DB servers
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
      
- hosts: controller
  become: true
  tasks:
  
  -  name: install unzip package
     package:
      name: unzip
  
  - name: unarchieve and install teraform 
    unarchive: 
      src: https://releases.hashicorp.com/terraform/0.15.4/terraform_0.15.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755 

   
