---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes

  - name: install httpd package
    yum:
      name: httpd
      state: latest

  - name: install sysstat package
    yum:
      name: sysstat
      state: latest
