---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
     update_cache: yes
    when: ansible_distribution == "CentOS"  

  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install php 
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

## Condition to install and update cache on Ubuntu OS.
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
        
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install php package
    apt:
      name: 
      state: latest
    when: ansible_distribution == "Ubuntu"
