---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (centOS)
    tags: always
    package:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"
  
  - name: update repository index (Ubuntu)
    tags: always
    package:
      update_cache: yes
    changed_when: flase
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
   - base

- hosts: db_servers
  become: true
  roles: 
   - db_servers

- hosts: web_servers
  become: true
  roles:
   - web_servers

- hosts: file_servers
  become: true
  roles:
   - file_servers

- hosts: controller
  become: true
  roles:
   - controller
