---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    tags: always    # since, we wanted to run it always regardless of any tags.
    yum:
     update_cache: yes
     update_only: yes
    when: ansible_distribution == "CentOS"  

  - name: install httpd and php package
    tags: apache, CentOS, httpd, php
    yum:
      name:
       - httpd
       - php
      state: latest
    when: ansible_distribution == "CentOS"


  - name: Update repository index
    tags: always
    apt:
     update_cache: yes
     upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    tags: apache, apache2, Ubuntu, php
    apt:
      name: 
       - apache2
       - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb on DB servers
    tags: db, mariadb, 
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"


- hosts: file_servers
  become: true
  tasks:
  - name: install samba pkg on file servers
    tags: samba, CentOS
    yum:
      name: samba
      state: latest
    when: ansible_distribution == "CentOS"

