- name: copy SSH for test_user
  tags: always
  authorized_key:
    user: test_user
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILbrN5h0evHn3EjZFiUtVTG2aYVNdHAjH1Q5VSgyMZbX ansible"

- name: Generate sshd_config file from template
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd         # since this is a handler input so we have to create a handler as well for sshd restart

